# Use an official Node runtime as the base image
FROM node:18.17.0

# Set the working directory
WORKDIR /app/client

# Copy package.json and package-lock.json to the container
COPY ./Client/package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code
COPY ./Client ./

# Start the application
CMD ["npm", "start"]
